version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "3000:3000"
    environment:
      - CMS_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTc5MDY5NjkxNSwiaWQiOiJ6Zm8wNnI1OTg4aW9qbnciLCJyZWZyZXNoYWJsZSI6ZmFsc2UsInR5cGUiOiJhdXRoIn0.nxjer_a8Hp3iQONtJhexVKqHIHsShvlqGqhVEsFkoVE
      - CMS_API_BASE=http://cms:8090
    depends_on:
      cms:
        condition: service_healthy
    restart: unless-stopped
  
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: pocketbase-cms
    ports:
      - "8090:8090"
    volumes:
      - ./cms/pb_data:/app/pb_data
      - ./cms/pb_migrations:/app/pb_migrations
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL:-admin@example.com}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD:-password123}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
